sudo: required

language: c

services:
    - docker

script:
    - docker run -v $PWD:/basalt -t jklmnn/componolit-ci:latest-gnat /bin/sh -c "gprbuild -P /basalt/test/aunit/test.gpr && /basalt/test/aunit/obj/test && gnatprove -P /basalt/test/proof/proof.gpr --level=2 --report=all --checks-as-errors"
